# Site settings
title: underhand-lab
email: skysea001010@gmail.com
url: https://underhand-lab.github.io
baseurl: 
description: "컴퓨터 기술을 이용한 야구 이해"
keywords: "Baseball"
locale: ko_KR
meta_author: Lee Ji-Heon

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6799fa # User Identity Color
  primary-rgb: "103, 153, 250"
  secondary: 1e293b # Slate 800
  secondary-dark: 0f172a # Slate 900

# Footer settings
footer:
  copyright: 이지헌 (EasyH)
  location: Location
  social: Around the Web
  credits: Credits

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: /project/:title

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
      values:
      permalink: ""

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

collections:
  about:
    output: false
